**IMPORTANT**
**To see your profile pic etc. enter your steam api key into api_key.json (gets generated after first launch)
get it here => https://steamcommunity.com/dev/apikey**

![0 22 3_Screenshot 2022-06-02 184458](https://user-images.githubusercontent.com/55054756/171681747-0bac0f83-d65d-457e-9a7e-1213ebf275a9.png)